### ISSUE TITLE
Mode cdc from mysql to postgres has an error on an ENUM column

### ISSUE THREAD

**Issue by mstephano** [slotix/dbconvert-streams-public#32]
My MySQL database has a table with a column of type `enum('PROPERTY')`, so that column has been created in postgres of type `varchar(8)`.

When running the mode cdc to live convert from mysql to postgres, I get this error message:
```sh
target-writer  | [2024/04/27 22:04:43] [error] target/target.go:362 failed to insert into table mytable: ERROR: COPY from stdin failed: unable to encode 1 into binary format for varchar (OID 1043): cannot find encode plan (SQLSTATE 57014)
```

However, doing mode convert instead is working fine. It can copy all the records without issues for this table.

Thank you in advanced!

**Comment by slotix** [comment]
fixed in [version 0.10.15 ](https://stream.dbconvert.com/releases-2024#version-0-10-15)

**Comment by mstephano** [comment]
@slotix Thank you so much for the quick fix, this is awesome! And before I forget, let me thank you for your project. I have been searching for a live convert for quite some time and yours is easy to use and it is working very well.

I am also trying to run your mode cdc on each of my 20 databases in my MySQL instance, and have other error logs. I was wondering if I should post each error as an issue in your repo, or should I create one issue and put them all under it?

**Comment by mstephano** [comment]
I just tested mode cdc on a database that was working fine on v0.10.12, but now have this error on v0.10.15. I am not sure of the table neither the column:

```sh
-- 1-million-records % docker-compose logs -f dbs-target-writer
target-writer  | DBConvert Streams Target Writer: starting at dbs-target-writer:8022
target-writer  | Version: v0.10.15  Build time: 2024-04-28_19:14:46
target-writer  | Find more information at https://stream.dbconvert.com
target-writer  | [2024/04/29 04:48:08] [info] connected to EventHub. Host: nats:4222
target-writer  | 2024-04-29 04:48:08.461585881 +0000 UTC m=+2.175248461 write error: nats: no response from stream
target-writer  | [2024/04/29 04:48:09] [info] subscribed to 'jobs.target'. Ready to receive new streams.
target-writer  | 2024-04-29 04:48:09.003854714 +0000 UTC m=+2.717516628 write error: nats: no response from stream
target-writer  | [2024/04/29 04:48:12] [info] dbs-target-writer/main.go:166 received stream configuration. ID: 2flC58THN2BkLt0LwTCMPkXsw8P
target-writer  | [2024/04/29 04:48:12] [info] target/target.go:80 connected to target database: Type: PostgreSQL | Host: postgres-target | User: postgres | Password: ***** | Database: postgres
target-writer  | panic: runtime error: slice bounds out of range [2:0]
target-writer  | 
target-writer  | goroutine 43 [running]:
target-writer  | github.com/slotix/dbconvert-stream/internal/dbengine.(*DBEngine).fixPostgresTypes(0xc09600?, 0xc0000a76c0?)
target-writer  | 	/home/dm3/dbconvert/dbconvert-stream/internal/dbengine/postgres.fixes.go:82 +0x3fb
target-writer  | github.com/slotix/dbconvert-stream/internal/dbengine.init.func1(0xbb8a20?, 0xc000034c30?)
target-writer  | 	/home/dm3/dbconvert/dbconvert-stream/internal/dbengine/dbengine.go:38 +0x13
target-writer  | github.com/slotix/dbconvert-stream/internal/dbengine.(*DBEngine).CreateTableDDL(0xc0001c8d40, {0xdec5c0, 0xc0001008c0}, {0xc00071801a, 0x7})
target-writer  | 	/home/dm3/dbconvert/dbconvert-stream/internal/dbengine/dbengine.go:360 +0x11e
target-writer  | github.com/slotix/dbconvert-stream/target.(*Target).CreateTable(0xc0004e8000, {0xdec5c0?, 0xc0001008c0?}, 0xc0005a6900)
target-writer  | 	/home/dm3/dbconvert/dbconvert-stream/target/table.go:77 +0x54
target-writer  | github.com/slotix/dbconvert-stream/target.(*Target).ProcessTableStructures(0xc0004e8000, {0xdec5c0, 0xc0001008c0}, 0x1)
target-writer  | 	/home/dm3/dbconvert/dbconvert-stream/target/table.go:41 +0x38d
target-writer  | main.(*server).jobsMsgHandler(0xc0000a4f00, {0xdf1f78, 0xc000048760})
target-writer  | 	/home/dm3/dbconvert/dbconvert-stream/cmd/dbs-target-writer/main.go:205 +0x505
target-writer  | github.com/nats-io/nats.go/jetstream.(*pullConsumer).Consume.func1(0xc0004a5490)
target-writer  | 	/home/dm3/go/pkg/mod/github.com/nats-io/nats.go@v1.34.0/jetstream/pull.go:245 +0x2be
target-writer  | github.com/nats-io/nats%2ego.(*Conn).waitForMsgs(0xc0000dd808, 0xc0004ba0e0)
target-writer  | 	/home/dm3/go/pkg/mod/github.com/nats-io/nats.go@v1.34.0/nats.go:3106 +0x412
target-writer  | created by github.com/nats-io/nats%2ego.(*Conn).subscribeLocked in goroutine 1
target-writer  | 	/home/dm3/go/pkg/mod/github.com/nats-io/nats.go@v1.34.0/nats.go:4320 +0x3a8
-- 1-million-records % 
```

**Comment by slotix** [comment]
You can track this matter on https://github.com/slotix/dbconvert-streams-public/issues/31. It's been relocated there.

**Comment by slotix** [comment]
> @slotix Thank you so much for the quick fix, this is awesome! And before I forget, let me thank you for your project. I have been searching for a live convert for quite some time and yours is easy to use and it is working very well.

@mstephano You're very welcome! I'm thrilled to hear that you're finding DBConvert Streams useful and that it's meeting your needs. Your positive feedback means a lot to us! If you have a moment, we'd love for you to share your thoughts and participate in our polls. Your input helps us continue improving the project. You can find the polls [here](https://github.com/slotix/dbconvert-streams-public/discussions/categories/polls). 

Thanks again for your support!
