### ISSUE TITLE
got new errors with new db.

### ISSUE THREAD

**Issue by slotix** [slotix/dbconvert-streams-public#5]
got new errors with new db.
ddl https://pastebin.com/y2KGEJ3G
```
DBConvert Stream Target Writer: starting at 0.0.0.0:8022
Version: v0.8.1  Build time: 2023-11-12_13:31:13
Find more information at https://stream.dbconvert.com
Handle metadata: true[2023/11/15 14:51:36] [info] eventhub/eventhub.go:69 connected to EventHub:  {"address": "nats://127.0.0.1:4222"}
[2023/11/15 14:51:50] [info] dbs-target-writer/main.go:142 [target] received stream configuration: 2YD96uD1w0Uofj7dt2ovCbNpVtb
[2023/11/15 14:51:50] [info] target/target.go:83 init target database: {"type":"PostgreSQL","host":"*","user":"postgres","password":"[REDACTED]","database":"test4"}

[2023/11/15 14:51:50] [info] target/table.go:47 HandleMeta: true
[2023/11/15 14:51:50] [error] target/table.go:50 ERROR: type "enum" does not exist (SQLSTATE 42704)DDL:
 &{CREATE TABLE IF NOT EXISTS "public"."logs_20231112" ("id" BIGSERIAL PRIMARY KEY  NOT NULL, "env" VARCHAR(255) NOT NULL, "user_id" BIGINT NULL, "ip" VARCHAR(45) NOT NULL, "message" VARCHAR(500) NOT NULL, "level" ENUM DEFAULT 'INFO' NOT NULL, "context" TEXT NULL, "extra" TEXT NULL, "created_at" TIMESTAMP NULL, "updated_at" TIMESTAMP NULL);  [CREATE INDEX "IDX_logs_20231112_logs_updated_at_index" ON "logs_20231112" ("updated_at") CREATE INDEX "IDX_logs_20231112_logs_user_id_index" ON "logs_20231112" ("user_id") CREATE INDEX "IDX_logs_20231112_logs_created_at_index" ON "logs_20231112" ("created_at") CREATE INDEX "IDX_logs_20231112_logs_env_index" ON "logs_20231112" ("env") CREATE INDEX "IDX_logs_20231112_logs_level_index" ON "logs_20231112" ("level") CREATE INDEX "IDX_logs_20231112_logs_message_fulltext" ON "logs_20231112" ("message")]}
[2023/11/15 14:51:50] [error] target/table.go:56 ERROR: relation "logs_20231112" does not exist (SQLSTATE 42P01)DDL:
 &{CREATE TABLE IF NOT EXISTS "public"."logs_20231112" ("id" BIGSERIAL PRIMARY KEY  NOT NULL, "env" VARCHAR(255) NOT NULL, "user_id" BIGINT NULL, "ip" VARCHAR(45) NOT NULL, "message" VARCHAR(500) NOT NULL, "level" ENUM DEFAULT 'INFO' NOT NULL, "context" TEXT NULL, "extra" TEXT NULL, "created_at" TIMESTAMP NULL, "updated_at" TIMESTAMP NULL);  [CREATE INDEX "IDX_logs_20231112_logs_updated_at_index" ON "logs_20231112" ("updated_at") CREATE INDEX "IDX_logs_20231112_logs_user_id_index" ON "logs_20231112" ("user_id") CREATE INDEX "IDX_logs_20231112_logs_created_at_index" ON "logs_20231112" ("created_at") CREATE INDEX "IDX_logs_20231112_logs_env_index" ON "logs_20231112" ("env") CREATE INDEX "IDX_logs_20231112_logs_level_index" ON "logs_20231112" ("level") CREATE INDEX "IDX_logs_20231112_logs_message_fulltext" ON "logs_20231112" ("message")]}
[2023/11/15 14:51:50] [info] target/table.go:61 [target] table 'logs_20231112' created or already exists
[2023/11/15 14:51:50] [info] target/table.go:47 HandleMeta: true
[2023/11/15 14:51:50] [error] target/table.go:50 ERROR: type "enum" does not exist (SQLSTATE 42704)DDL:
 &{CREATE TABLE IF NOT EXISTS "public"."logs" ("id" BIGSERIAL PRIMARY KEY  NOT NULL, "env" VARCHAR(255) NOT NULL, "user_id" BIGINT NULL, "ip" VARCHAR(45) NOT NULL, "message" VARCHAR(500) NOT NULL, "level" ENUM DEFAULT 'INFO' NOT NULL, "context" TEXT NULL, "extra" TEXT NULL, "created_at" TIMESTAMP NULL, "updated_at" TIMESTAMP NULL);  [CREATE INDEX "IDX_logs_logs_user_id_index" ON "logs" ("user_id") CREATE INDEX "IDX_logs_logs_created_at_index" ON "logs" ("created_at") CREATE INDEX "IDX_logs_logs_env_index" ON "logs" ("env") CREATE INDEX "IDX_logs_logs_level_index" ON "logs" ("level") CREATE INDEX "IDX_logs_logs_message_fulltext" ON "logs" ("message") CREATE INDEX "IDX_logs_logs_updated_at_index" ON "logs" ("updated_at")]}
[2023/11/15 14:51:50] [error] target/table.go:56 ERROR: relation "logs" does not exist (SQLSTATE 42P01)DDL:
 &{CREATE TABLE IF NOT EXISTS "public"."logs" ("id" BIGSERIAL PRIMARY KEY  NOT NULL, "env" VARCHAR(255) NOT NULL, "user_id" BIGINT NULL, "ip" VARCHAR(45) NOT NULL, "message" VARCHAR(500) NOT NULL, "level" ENUM DEFAULT 'INFO' NOT NULL, "context" TEXT NULL, "extra" TEXT NULL, "created_at" TIMESTAMP NULL, "updated_at" TIMESTAMP NULL);  [CREATE INDEX "IDX_logs_logs_user_id_index" ON "logs" ("user_id") CREATE INDEX "IDX_logs_logs_created_at_index" ON "logs" ("created_at") CREATE INDEX "IDX_logs_logs_env_index" ON "logs" ("env") CREATE INDEX "IDX_logs_logs_level_index" ON "logs" ("level") CREATE INDEX "IDX_logs_logs_message_fulltext" ON "logs" ("message") CREATE INDEX "IDX_logs_logs_updated_at_index" ON "logs" ("updated_at")]}
[2023/11/15 14:51:50] [info] target/table.go:61 [target] table 'logs' created or already exists
[2023/11/15 14:51:50] [info] target/table.go:47 HandleMeta: true
[2023/11/15 14:51:50] [error] target/table.go:50 ERROR: type "enum" does not exist (SQLSTATE 42704)DDL:
 &{CREATE TABLE IF NOT EXISTS "public"."logs_20231105" ("id" BIGSERIAL PRIMARY KEY  NOT NULL, "env" VARCHAR(255) NOT NULL, "user_id" BIGINT NULL, "ip" VARCHAR(45) NOT NULL, "message" VARCHAR(500) NOT NULL, "level" ENUM DEFAULT 'INFO' NOT NULL, "context" TEXT NULL, "extra" TEXT NULL, "created_at" TIMESTAMP NULL, "updated_at" TIMESTAMP NULL);  [CREATE INDEX "IDX_logs_20231105_logs_env_index" ON "logs_20231105" ("env") CREATE INDEX "IDX_logs_20231105_logs_level_index" ON "logs_20231105" ("level") CREATE INDEX "IDX_logs_20231105_logs_message_fulltext" ON "logs_20231105" ("message") CREATE INDEX "IDX_logs_20231105_logs_updated_at_index" ON "logs_20231105" ("updated_at") CREATE INDEX "IDX_logs_20231105_logs_user_id_index" ON "logs_20231105" ("user_id") CREATE INDEX "IDX_logs_20231105_logs_created_at_index" ON "logs_20231105" ("created_at")]}
[2023/11/15 14:51:50] [error] target/table.go:56 ERROR: relation "logs_20231105" does not exist (SQLSTATE 42P01)DDL:
 &{CREATE TABLE IF NOT EXISTS "public"."logs_20231105" ("id" BIGSERIAL PRIMARY KEY  NOT NULL, "env" VARCHAR(255) NOT NULL, "user_id" BIGINT NULL, "ip" VARCHAR(45) NOT NULL, "message" VARCHAR(500) NOT NULL, "level" ENUM DEFAULT 'INFO' NOT NULL, "context" TEXT NULL, "extra" TEXT NULL, "created_at" TIMESTAMP NULL, "updated_at" TIMESTAMP NULL);  [CREATE INDEX "IDX_logs_20231105_logs_env_index" ON "logs_20231105" ("env") CREATE INDEX "IDX_logs_20231105_logs_level_index" ON "logs_20231105" ("level") CREATE INDEX "IDX_logs_20231105_logs_message_fulltext" ON "logs_20231105" ("message") CREATE INDEX "IDX_logs_20231105_logs_updated_at_index" ON "logs_20231105" ("updated_at") CREATE INDEX "IDX_logs_20231105_logs_user_id_index" ON "logs_20231105" ("user_id") CREATE INDEX "IDX_logs_20231105_logs_created_at_index" ON "logs_20231105" ("created_at")]}
[2023/11/15 14:51:50] [info] target/table.go:61 [target] table 'logs_20231105' created or already exists
[2023/11/15 14:51:51] [error] postgresql/database.go:191 statement description failed: ERROR: relation "public.logs_20231112" does not exist (SQLSTATE 42P01)
[2023/11/15 14:51:51] [error] postgresql/database.go:191 statement description failed: ERROR: relation "public.logs_20231112" does not exist (SQLSTATE 42P01)
panic: interface conversion: interface {} is time.Time, not string

goroutine 187 [running]:
github.com/slotix/dbconvert-stream/internal/dbengine.(*Table).CastDateTimeTypes(0xc0003b5dd0, {0xc000eca000, 0xa, 0xe79890?})
        /home/dm3/dbconvert/dbconvert-stream/internal/dbengine/table.go:50 +0x1d9
github.com/slotix/dbconvert-stream/target/postgresql.processInsertEvent({0xe79890, 0x152e120}, 0xc0003b5dd0, {0x89a35c30, 0x0, 0x0, {0xc0000e4000, 0x28, 0x40}, 0x0}, ...)
        /home/dm3/dbconvert/dbconvert-stream/target/postgresql/database.go:221 +0x19c
github.com/slotix/dbconvert-stream/target/postgresql.(*Database).ProcessData.func1({0xe79890?, 0x152e120?}, {0xe7f508?, 0xc00047e4b0?})
        /home/dm3/dbconvert/dbconvert-stream/target/postgresql/database.go:156 +0x51
github.com/slotix/dbconvert-stream/target/postgresql.(*Database).withTx(0xc0000123f0, 0xc00016fcc8)
        /home/dm3/dbconvert/dbconvert-stream/target/postgresql/database.go:189 +0x1db
github.com/slotix/dbconvert-stream/target/postgresql.(*Database).ProcessData(0xb7ed49?, 0x37d49b177b2?, {0x89a35c30, 0x0, 0x0, {0xc0000e4000, 0x28, 0x40}, 0x0})
        /home/dm3/dbconvert/dbconvert-stream/target/postgresql/database.go:155 +0x19b
github.com/slotix/dbconvert-stream/target.(*Target).processData(0xc0003921e0, {0x89a35c30, 0x0, 0x0, {0xc0000e4000, 0x28, 0x40}, 0x0})
        /home/dm3/dbconvert/dbconvert-stream/target/target.go:282 +0x83
github.com/slotix/dbconvert-stream/target.(*Target).workerFunc(0xc0003921e0, {0xe79900, 0xc00084ab40}, 0x0?, 0x0?)
        /home/dm3/dbconvert/dbconvert-stream/target/target.go:198 +0x2ad
created by github.com/slotix/dbconvert-stream/target.(*Target).startWorkerPool in goroutine 56
        /home/dm3/dbconvert/dbconvert-stream/target/target.go:144 +0x45
```

_Originally posted by @TristisOris in https://github.com/slotix/dbconvert-streams-public/issues/4#issuecomment-1812407368_

**Comment by slotix** [comment]
@TristisOris , could you, please provide some records from logs to debug the issue with panic: interface conversion: interface {} is time.Time, not string ? 
thanks

**Comment by TristisOris** [comment]
```
id,env,user_id,ip,message,level,context,extra,created_at,updated_at
79,production,0,127.0.0.1,ScienceApplication e23e307d-c3f2-4485-b361-b8647217f6ad parent 2308-047,INFO,[],[],2023-11-12 00:00:40,2023-11-12 00:00:40
84,production,0,127.0.0.1,ScienceApplication a654706a-ce1b-4eb0-be2d-d78ad40aa54d parent 2311-011,INFO,[],[],2023-11-12 00:00:40,2023-11-12 00:00:40
89,production,0,127.0.0.1,ScienceApplication 7cb30f25-b158-46dd-b41f-c585a4cf0cca parent 2308-074,INFO,[],[],2023-11-12 00:00:41,2023-11-12 00:00:41
94,production,0,127.0.0.1,SCIENCE_APPLICATION_FUNDING_SOURCE:CREATED:10764369,INFO,{"App\\Model\\Science\\Application\\ScienceApplicationFundingSource":"{\"company_id\":11413,\"source_id\":17256,\"kbp_id\":null,\"volume\":0,\"science_application_id\":317029,\"updated_at\":\"2023-11-11T21:00:40.000000Z\",\"created_at\":\"2023-11-11T21:00:40.000000Z\",\"id\":10764369,\"kbp\":[]}"},[],2023-11-12 00:00:41,2023-11-12 00:00:41
99,production,0,127.0.0.1,SCIENCE_APPLICATION_FUNDING_SOURCE:CREATED:10764364,INFO,{"App\\Model\\Science\\Application\\ScienceApplicationFundingSource":"{\"company_id\":52680,\"source_id\":17256,\"kbp_id\":null,\"volume\":0,\"science_application_id\":317009,\"updated_at\":\"2023-11-11T21:00:40.000000Z\",\"created_at\":\"2023-11-11T21:00:40.000000Z\",\"id\":10764364,\"kbp\":[]}"},[],2023-11-12 00:00:41,2023-11-12 00:00:41
374,production,0,127.0.0.1,PURE_CACHE:UPDATED:4611366,INFO,{"App\\Model\\Pure\\PureCache":"{\"id\":4611366,\"uuid\":\"ee9071d2-216c-4204-8890-94cfcef3a9ad\",\"endpoint\":\"events\",\"raw\":\"<?xml version=\\\"1.0\\\"?>\\n<event xmlns:xsi=\\\"http:\\\/\\\/www.w3.org\\\/2001\\\/XMLSchema-instance\\\" uuid=\\\"73160d1e-c67c-4f77-a5a3-578bbed726eb\\\" pureId=\\\"102447150\\\" xsi:schemaLocation=\\\"http:\\\/\\\/localhost:8080\\\/ws\\\/api\\\/522 http:\\\/\\\/localhost:8080\\\/ws\\\/api\\\/522\\\/xsd\\\/schema1.xsd\\\"><renderings><rendering format=\\\"short\\\">&lt;div class=\\\"rendering rendering_event rendering_short rendering_event_short\\\"&gt;&lt;h2 class=\\\"title\\\"&gt;&lt;span&gt;&#x422;&#x415;&#x41D;&#x414;&#x415;&#x41D;&#x426;&#x418;&#x418; &#x41F;&#x420;&#x41E;&#x421;&#x422;&#x420;&#x410;&#x41D;&#x421;&#x422;&#x412;&#x415;&#x41D;&#x41D;&#x41E;&#x413;&#x41E; &#x420;&#x410;&#x417;&#x412;&#x418;&#x422;&#x418;&#x42F; &#x421;&#x41E;&#x412;&#x420;&#x415;&#x41C;&#x415;&#x41D;&#x41D;&#x41E;&#x419; &#x420;&#x41E;&#x421;&#x421;&#x418;&#x418; &#x418; &#x41F;&#x420;&#x418;&#x41E;&#x420;&#x418;&#x422;&#x415;&#x422;&#x42B; &#x415;&#x413;&#x41E; &#x420;&#x415;&#x413;&#x423;&#x41B;&#x418;&#x420;&#x41E;&#x412;&#x410;&#x41D;&#x418;&#x42F;: XIII &#x415;&#x436;&#x435;&#x433;&#x43E;&#x434;&#x43D;&#x430;&#x44F; &#x43D;&#x430;&#x443;&#x447;&#x43D;&#x430;&#x44F; &#x410;&#x441;&#x441;&#x430;&#x43C;&#x431;&#x43B;&#x435;&#x44F; &#x410;&#x420;&#x413;&#x41E;&lt;\\\/span&gt;&lt;\\\/h2&gt;&lt;p&gt;&lt;span class=\\\"date\\\"&gt;12\\\/09\\\/22&lt;\\\/span&gt; &#x2192; &lt;span class=\\\"date\\\"&gt;17\\\/09\\\/22&lt;\\\/span&gt;&lt;\\\/p&gt;&#x422;&#x44E;&#x43C;&#x435;&#x43D;&#x44C;, &#x420;&#x43E;&#x441;&#x441;&#x438;&#x439;&#x441;&#x43A;&#x430;&#x44F; &#x424;&#x435;&#x434;&#x435;&#x440;&#x430;&#x446;&#x438;&#x44F;&lt;p class=\\\"type\\\"&gt;&lt;span class=\\\"type_family\\\"&gt;&#x421;&#x43E;&#x431;&#x44B;&#x442;&#x438;&#x435;&lt;span class=\\\"type_family_sep\\\"&gt;: &lt;\\\/span&gt;&lt;\\\/span&gt;&lt;span class=\\\"type_classification\\\"&gt;&#x43A;&#x43E;&#x43D;&#x444;&#x435;&#x440;&#x435;&#x43D;&#x446;&#x438;&#x44F;&lt;\\\/span&gt;&lt;\\\/p&gt;&lt;\\\/div&gt;<\\\/rendering><rendering format=\\\"long\\\">&lt;div class=\\\"rendering rendering_event rendering_long rendering_event_long\\\"&gt;&lt;h2 class=\\\"title\\\"&gt;&lt;span&gt;&#x422;&#x415;&#x41D;&#x414;&#x415;&#x41D;&#x426;&#x418;&#x418; &#x41F;&#x420;&#x41E;&#x421;&#x422;&#x420;&#x410;&#x41D;&#x421;&#x422;&#x412;&#x415;&#x41D;&#x41D;&#x41E;&#x413;&#x41E; &#x420;&#x410;&#x417;&#x412;&#x418;&#x422;&#x418;&#x42F; &#x421;&#x41E;&#x412;&#x420;&#x415;&#x41C;&#x415;&#x41D;&#x41D;&#x41E;&#x419; &#x420;&#x41E;&#x421;&#x421;&#x418;&#x418; &#x418; &#x41F;&#x420;&#x418;&#x41E;&#x420;&#x418;&#x422;&#x415;&#x422;&#x42B; &#x415;&#x413;&#x41E; &#x420;&#x415;&#x413;&#x423;&#x41B;&#x418;&#x420;&#x41E;&#x412;&#x410;&#x41D;&#x418;&#x42F;: XIII &#x415;&#x436;&#x435;&#x433;&#x43E;&#x434;&#x43D;&#x430;&#x44F; &#x43D;&#x430;&#x443;&#x447;&#x43D;&#x430;&#x44F; &#x410;&#x441;&#x441;&#x430;&#x43C;&#x431;&#x43B;&#x435;&#x44F; &#x410;&#x420;&#x413;&#x41E;&lt;\\\/span&gt;&lt;\\\/h2&gt;&lt;table class=\\\"properties\\\"&gt;&lt;tbody&gt;&lt;tr&gt;&lt;th scope=\\\"row\\\"&gt;&#x41F;&#x440;&#x43E;&#x434;&#x43E;&#x43B;&#x436;&#x438;&#x442;&#x435;&#x43B;&#x44C;&#x43D;&#x43E;&#x441;&#x442;&#x44C;&lt;\\\/th&gt;&lt;td&gt;&lt;span class=\\\"date\\\"&gt;12 &#x441;&#x435;&#x43D; 2022&lt;\\\/span&gt; &#x2192; &lt;span class=\\\"date\\\"&gt;17 &#x441;&#x435;&#x43D; 2022&lt;\\\/span&gt;&lt;\\\/td&gt;&lt;\\\/tr&gt;&lt;tr&gt;&lt;th scope=\\\"row\\\"&gt;&#x41C;&#x435;&#x441;&#x442;&#x43E;&#x43F;&#x43E;&#x43B;&#x43E;&#x436;&#x435;&#x43D;&#x438;&#x435;&lt;\\\/th&gt;&lt;td&gt;&#x420;&#x43E;&#x441;&#x441;&#x438;&#x44F;&lt;\\\/td&gt;&lt;\\\/tr&gt;&lt;tr&gt;&lt;th scope=\\\"row\\\"&gt;&#x413;&#x43E;&#x440;&#x43E;&#x434;&lt;\\\/th&gt;&lt;td&gt;&#x422;&#x44E;&#x43C;&#x435;&#x43D;&#x44C;&lt;\\\/td&gt;&lt;\\\/tr&gt;&lt;tr&gt;&lt;th scope=\\\"row\\\"&gt;&#x421;&#x442;&#x440;&#x430;&#x43D;&#x430;\\\/T&#x435;&#x440;&#x440;&#x438;&#x442;&#x43E;&#x440;&#x438;&#x44F;&lt;\\\/th&gt;&lt;td&gt;&#x420;&#x43E;&#x441;&#x441;&#x438;&#x439;&#x441;&#x43A;&#x430;&#x44F; &#x424;&#x435;&#x434;&#x435;&#x440;&#x430;&#x446;&#x438;&#x44F;&lt;\\\/td&gt;&lt;\\\/tr&gt;&lt;tr&gt;&lt;th scope=\\\"row\\\"&gt;&#x423;&#x440;&#x43E;&#x432;&#x435;&#x43D;&#x44C; &#x438;&#x437;&#x432;&#x435;&#x441;&#x442;&#x43D;&#x43E;&#x441;&#x442;&#x438;&lt;\\\/th&gt;&lt;td&gt;&#x43C;&#x435;&#x436;&#x434;&#x443;&#x43D;&#x430;&#x440;&#x43E;&#x434;&#x43D;&#x44B;&#x439; &#x443;&#x440;&#x43E;&#x432;&#x435;&#x43D;&#x44C; &lt;\\\/td&gt;&lt;\\\/tr&gt;&lt;\\\/tbody&gt;&lt;\\\/table&gt;&lt;p class=\\\"type\\\"&gt;&lt;span class=\\\"type_family\\\"&gt;&#x421;&#x43E;&#x431;&#x44B;&#x442;&#x438;&#x435;&lt;span class=\\\"type_family_sep\\\"&gt;: &lt;\\\/span&gt;&lt;\\\/span&gt;&lt;span class=\\\"type_classification\\\"&gt;&#x43A;&#x43E;&#x43D;&#x444;&#x435;&#x440;&#x435;&#x43D;&#x446;&#x438;&#x44F;&lt;\\\/span&gt;&lt;\\\/p&gt;&lt;\\\/div&gt;<\\\/rendering><\\\/renderings><title formatted=\\\"true\\\"><text locale=\\\"ru_RU\\\">&#x422;&#x415;&#x41D;&#x414;&#x415;&#x41D;&#x426;&#x418;&#x418; &#x41F;&#x420;&#x41E;&#x421;&#x422;&#x420;&#x410;&#x41D;&#x421;&#x422;&#x412;&#x415;&#x41D;&#x41D;&#x41E;&#x413;&#x41E; &#x420;&#x410;&#x417;&#x412;&#x418;&#x422;&#x418;&#x42F; &#x421;&#x41E;&#x412;&#x420;&#x415;&#x41C;&#x415;&#x41D;&#x41D;&#x41E;&#x419; &#x420;&#x41E;&#x421;&#x421;&#x418;&#x418; &#x418; &#x41F;&#x420;&#x418;&#x41E;&#x420;&#x418;&#x422;&#x415;&#x422;&#x42B; &#x415;&#x413;&#x41E; &#x420;&#x415;&#x413;&#x423;&#x41B;&#x418;&#x420;&#x41E;&#x412;&#x410;&#x41D;&#x418;&#x42F;<\\\/text><\\\/title><type pureId=\\\"1140\\\" uri=\\\"\\\/dk\\\/atira\\\/pure\\\/event\\\/eventtypes\\\/event\\\/conference\\\"><term formatted=\\\"false\\\"><text locale=\\\"ru_RU\\\">&#x43A;&#x43E;&#x43D;&#x444;&#x435;&#x440;&#x435;&#x43D;&#x446;&#x438;&#x44F;<\\\/text><\\\/term><\\\/type><subTitle formatted=\\\"true\\\"><text locale=\\\"ru_RU\\\">XIII &#x415;&#x436;&#x435;&#x433;&#x43E;&#x434;&#x43D;&#x430;&#x44F; &#x43D;&#x430;&#x443;&#x447;&#x43D;&#x430;&#x44F; &#x410;&#x441;&#x441;&#x430;&#x43C;&#x431;&#x43B;&#x435;&#x44F; &#x410;&#x420;&#x413;&#x41E;<\\\/text><\\\/subTitle><period><startDate>2022-09-12<\\\/startDate><endDate>2022-09-17<\\\/endDate><\\\/period><degreeOfRecognition pureId=\\\"2688\\\" uri=\\\"\\\/dk\\\/atira\\\/pure\\\/event\\\/degreeofrecognition\\\/international\\\"><term formatted=\\\"false\\\"><text locale=\\\"ru_RU\\\">&#x43C;&#x435;&#x436;&#x434;&#x443;&#x43D;&#x430;&#x440;&#x43E;&#x434;&#x43D;&#x44B;&#x439; &#x443;&#x440;&#x43E;&#x432;&#x435;&#x43D;&#x44C; <\\\/text><\\\/term><\\\/degreeOfRecognition><location>&#x420;&#x43E;&#x441;&#x441;&#x438;&#x44F;<\\\/location><city>&#x422;&#x44E;&#x43C;&#x435;&#x43D;&#x44C;<\\\/city><country pureId=\\\"597\\\" uri=\\\"\\\/dk\\\/atira\\\/pure\\\/core\\\/countries\\\/ru\\\"><term formatted=\\\"false\\\"><text locale=\\\"ru_RU\\\">&#x420;&#x43E;&#x441;&#x441;&#x438;&#x439;&#x441;&#x43A;&#x430;&#x44F; &#x424;&#x435;&#x434;&#x435;&#x440;&#x430;&#x446;&#x438;&#x44F;<\\\/text><\\\/term><\\\/country><workflow workflowStep=\\\"forApproval\\\"><value formatted=\\\"false\\\"><text locale=\\\"ru_RU\\\">&#x41D;&#x430; &#x43E;&#x434;&#x43E;&#x431;&#x440;&#x435;&#x43D;&#x438;&#x438;<\\\/text><\\\/value><\\\/workflow><info><createdBy>st004054<\\\/createdBy><createdDate>2023-01-28T20:31:50.517+03:00<\\\/createdDate><modifiedBy>st009313<\\\/modifiedBy><modifiedDate>2023-01-30T15:29:31.851+03:00<\\\/modifiedDate><usedContents><usedContent rendering=\\\"short\\\" locale=\\\"ru_RU\\\"><uuids><uuid family=\\\"Event\\\"><uuids><uuid>73160d1e-c67c-4f77-a5a3-578bbed726eb<\\\/uuid><\\\/uuids><\\\/uuid><uuid family=\\\"ClassificationScheme\\\"><uuids><uuid>e173dddc-857b-4afe-b011-776a3899fd99<\\\/uuid><uuid>a1e354b2-afae-4b62-a1da-6be8ed529ea3<\\\/uuid><\\\/uuids><\\\/uuid><\\\/uuids><\\\/usedContent><usedContent rendering=\\\"long\\\" locale=\\\"ru_RU\\\"><uuids><uuid family=\\\"Event\\\"><uuids><uuid>73160d1e-c67c-4f77-a5a3-578bbed726eb<\\\/uuid><\\\/uuids><\\\/uuid><uuid family=\\\"ClassificationScheme\\\"><uuids><uuid>e4262c15-ecde-4ad7-99d1-0e2b7b09d2cb<\\\/uuid><uuid>e173dddc-857b-4afe-b011-776a3899fd99<\\\/uuid><uuid>a1e354b2-afae-4b62-a1da-6be8ed529ea3<\\\/uuid><\\\/uuids><\\\/uuid><\\\/uuids><\\\/usedContent><\\\/usedContents><previousUuids><previousUuid>ee9071d2-216c-4204-8890-94cfcef3a9ad<\\\/previousUuid><\\\/previousUuids><\\\/info><\\\/event>\\n\"}"},[],2023-10-29 00:11:59,2023-10-29 00:11:59
379,production,0,127.0.0.1,SAVE ITEM FROM PURE: ee9071d2-216c-4204-8890-94cfcef3a9ad,INFO,[],[],2023-10-29 00:11:59,2023-10-29 00:11:59
384,production,0,127.0.0.1,ScienceEvent ee9071d2-216c-4204-8890-94cfcef3a9ad not found. Call import,DEBUG,[],[],2023-10-29 00:11:59,2023-10-29 00:11:59
```

**Comment by slotix** [comment]
Enums are now supported. Explore the release details at [DBS Releases](https://stream.dbconvert.com/dbs-releases#version-0-8-3).
